### ISSUE TITLE
Add to BioConductor

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/InterMineR#1]
https://www.bioconductor.org/developers/package-submission/

**Comment by julie-sullivan** [comment]
CRAN too

**Comment by rachellyne** [comment]
I'll test it.

**Comment by julie-sullivan** [comment]
@rachellyne The travis test failed on a dependency. I can't tell why. I tried to submit to CRAN but the form wouldn't accept my `.tar.gz` file. 

> Could not find DESCRIPTION file in archive or file is not readable

Maybe you could double check that you can use it first so I know I am doing the right thing.

**Comment by rachellyne** [comment]
Yes, I tried yesterday but was having trouble just importing into R or Rstudio.  I wish I had a memory as I must have done this before.

**Comment by julie-sullivan** [comment]
Skipping CRAN for now. None of the dependencies used are available on CRAN for some reason.

**Comment by julie-sullivan** [comment]
https://github.com/Bioconductor/Contributions/issues/393

**Comment by julie-sullivan** [comment]
Done!!
