### ISSUE TITLE
Should not be hard coded for humans (even though we ARE the best)

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/InterMineR#3]
See here: https://github.com/intermine/intermineR/blob/master/R/InterMineR.R

```
getRegionSequence <- function(im, regions, organism="H. sapiens", extension=100, isInterbase=F, timeout=60){
```

I believe there are other examples. The queries should be for all organisms not just people.

Tell @rachellyne

**Comment by AyushyaChitransh** [comment]
I was unable to find the hard coded lines mentioned in the referenced file. Has the issue been resolved, or is it in any other file?

**Comment by rachellyne** [comment]
Hi Ayushya,

Did you get this working?  The person working on this is currently away 
and I don't know how far they got with it.  Please let me know if it's 
still an issue,

Best Wishes,

Rachel.
