### ISSUE TITLE
Error in curl 

### ISSUE THREAD

**Issue by Hisquare** [intermine/InterMineR#53]
When I put the query code into a function, it does not go through. But when I run it plainly, it works.

It through this error;
Error in curl :: curl_fetch_memory(URL, handle = handle) :
Timeout was reached: Connection timed out after 10000 miliseconds

Or,

Failed to connect to registry. Intermine.org port 80: Timed out

I could blame the internet connection for this but it doesn't do that if I run it outside the function I wrote.

**Comment by julie-sullivan** [comment]
@Hisquare those are instructions for use on the command line, or in RStudio. If you are writing a script or writing a new method you might need different syntax.

For example:

```
Library (intermineR)
```
See: https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/library

That loads the library InterMineR. You probably only want to do that once, at the top of your script. 

I would suggest looking at the other methods in InterMineR to get examples, and taking a tutorial to get more familiar with how methods work in R.

**Comment by Hisquare** [comment]
OK. Thanks a lot..

I intentionally called the library inside the method though. I was testing
something. Anyways, it wasn't really a problem. It was just an issue of
internet connection..

😊
