### ISSUE TITLE
getModel function in intermineR not working

### ISSUE THREAD

**Issue by rachellyne** [intermine/InterMineR#63]
The getModel function does not work for FlyMine or humanMine.  It seems to be ok for mouseMine.  It seems to be a problem with rbind.  Error is "number of columns  of arguments do not match".   This is in the listModelSummary function which is called by the getModel function.

https://github.com/intermine/InterMineR/blob/master/R/InterMineR.R#L61

**Comment by julie-sullivan** [comment]
What is the `getModel()` function trying to do? It looks like it's just putting the values in a data structure. Why would that cause an error? Is it trying to merge anything?

Would a duplicate in the model be causing the issue? 

I don't know how an error in the model would cause an error in InterMineR but not in InterMine.

**Comment by julie-sullivan** [comment]
Use dplyr's bind_rows instead? Would that work? I don't see why there should be a different number of columns in the first place, if it's just the model?
