### ISSUE TITLE
Update citation guidelines

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMineR#66]
We're still asking people to cite the 2012 paper, but it makes more sense to cite the InterMineR paper I think. 

See https://bioconductor.org/packages/release/bioc/html/InterMineR.html (side note: we should update the maintainer email address, as well)

**Comment by rachellyne** [comment]
I've already updated this - it should come out with the next Bioconductor release.

**Comment by yochannah** [comment]
ah, perfect! I got an email notification about a citation today and it was using the older paper.
