### ISSUE TITLE
Bad Request (HTTP 400) when runQuery

### ISSUE THREAD

**Issue by carlotta-93** [intermine/InterMineR#67]
Hi,
I wrote the following function to retrieve gene information from a list of genes for Arabidopsis thaliana.

```r
getGeneNames <- function(gene_ids){
  thaliana = initInterMine(listMines()["ThaleMine"])
  # gene_ids <- list(rownames(all_transcript_0))
  # build constraints
  constraints = InterMineR::setConstraints(
    paths = c("Gene"),
    operators = "LOOKUP",
    values = list(gene_ids)
  )
  
  print("constraints built")
  
  # define new query
  queryGeneIds = InterMineR::setQuery(
    select = c(
      "Gene.primaryIdentifier",
      "Gene.symbol",
      "Gene.briefDescription",
      "Gene.chromosome.primaryIdentifier"
      # "Gene.geneRifs.annotation"
      # "Gene.chromosomeLocation.start",
      # "Gene.chromosomeLocation.end",
      # "Gene.chromosomeLocation.strand"
    ),
    where = constraints
  ) 

  # run query and store results
  print("running query, please wait...")
  gene_info = InterMineR::runQuery(im = thaliana, qry = queryGeneIds)
  
  # rename columns
  colnames(gene_info) <- c("meta.gene_id", "gene_name", "gene_description", "chromosome")
  return(gene_info)
}
```

For some reason it stopped working few months ago, throwing the error: 
**Error in InterMineR::runQuery(im = thaliana, qry = queryGeneIds) : 
  Bad Request (HTTP 400).**

sessionInfo: 
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1
nickname       Action of the Toes

[5] InterMineR_1.6.1  

Can anyone help me figuring out what is going on ? Am i missing something ?

**Comment by yochannah** [comment]
Hey @carlotta-93 - sorry for the slow reply on this one - did you manage to sort it?

**Comment by carlotta-93** [comment]
Hi @yochannah,
Yes. The error was in the input format. I closed the issue as soon as I noticed.
