### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/InterMineR#8]
Why is it failing?

`R for Travis-CI is not officially supported, but is community maintained.`

Should we even bother?

**Comment by julie-sullivan** [comment]
```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

Error: 'BiocInstaller' must be installed to install Bioconductor packages

Execution halted

The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

**Comment by julie-sullivan** [comment]
https://docs.travis-ci.com/user/languages/r/

Maybe will work once we have bioconductor?

**Comment by julie-sullivan** [comment]
```
Error: processing vignette 'InterMineR.Rnw' failed with diagnostics:

 chunk 5 

Error : Please install xml2 package

Execution halted
```

I thought it got all packages from the DESCRIPTION file?

**Comment by julie-sullivan** [comment]
```
Error: processing vignette 'InterMineR.Rnw' failed with diagnostics:

 chunk 8 

Error in rbind(deparse.level, ...) : 

  numbers of columns of arguments do not match

Execution halted

The command "R CMD build  ." failed and exited with 1 during .

Your build has been stopped.
```

**Comment by kostaskyritsis** [comment]
In https://docs.travis-ci.com/user/languages/r/ there is a section that mentions adding `r: bioc-devel` for Bioconductor dependencies.

@julie-sullivan based on this closed issue: https://github.com/travis-ci/travis-ci/issues/6431 and this modification of .travis.yml: https://github.com/leekgroup/recount/commit/3bbd47f07eeb4a337ed47102b4f12267e42965d1 perhaps the problem with BiocInstaller can be solved by editing the .travis.yml:

`language: r
r: bioc-devel
sudo: true
cache: packages
warnings_are_errors: false

bioc_required: true
bioc_use_devel: true`

Furthermore, in https://github.com/travis-ci/travis-ci/issues/6431 it is mentioned that `cache: true` was removed although this may not play a role in the issue.

**Comment by kostaskyritsis** [comment]
For xml2 package perhaps adding the line

```
r_packages: 
- xml2
```

.travis.yml will directly specify the package?



The error:
```
Error in rbind(deparse.level, ...) : 

  numbers of columns of arguments do not match
```

is exactly what I got from applying the getModel() function in HumanMine before the fix, so may the problem is there?

**Comment by julie-sullivan** [comment]
@kostaskyritsis oh okay! so maybe when we merge your fix into the code, this error will be fixed?

**Comment by kostaskyritsis** [comment]
@julie-sullivan Yeah I think that the InterMineR.Rnw should work afterwards.

**Comment by julie-sullivan** [comment]
Travis is working!
